#!/usr/bin/env python3
"""Synthetic data generation via OpenRouter API.

=== GENERATION ATTRIBUTION ===
Base script generated by: KAT-Coder V2.5 Dev APEX I-Mini (local, 131k ctx)
Prompt: deepseek-v4-pro (via opencode)
Bug fixes and enhancements by: deepseek-v4-pro

KAT-Coder produced a correct skeletal structure (async openai client,
retry with backoff, JSONL output, tqdm, CLI args) with 3 bugs:
  1. `from tqdm import asyncio as tqdm_asyncio` — tqdm.asyncio doesn't exist
  2. `signal.signal(signal.SIGINT, self._handle_signal)` — bound method
     loses `self`, causing AttributeError on shutdown
  3. `asyncio.gather` + manual Queue — race between gather completion
     and Queue draining; drops results on early shutdown

deepseek-v4-pro fixes inline below, marked with `[FIXED by dsv4-pro]`.
=== END ATTRIBUTION ===

Usage:
    export OPENROUTER_API_KEY=sk-or-...
    python scripts/synthetic-data.py --num-samples 100 --concurrency 5

    # With a custom prompt template file (one prompt per line):
    python scripts/synthetic-data.py --prompt-file prompts.txt

    # With a single prompt repeated:
    python scripts/synthetic-data.py --prompt "Write a Python function to sort a list" --num-samples 50
"""

import argparse
import asyncio
import json
import os
import signal
import sys
import time
import uuid
from datetime import datetime, timezone

from openai import AsyncOpenAI
from tqdm import tqdm  # [FIXED by dsv4-pro] KAT-Coder wrote `from tqdm import asyncio as tqdm_asyncio` — tqdm.asyncio submodule doesn't exist


def parse_args():
    parser = argparse.ArgumentParser(description="Generate synthetic data via OpenRouter API")
    parser.add_argument("--model", default="google/gemini-2.5-flash", help="OpenRouter model name")
    parser.add_argument("--num-samples", type=int, default=100, help="Number of samples to generate")
    parser.add_argument("--output", default="synthetic_data.jsonl", help="Output JSONL file path")
    parser.add_argument("--concurrency", type=int, default=5, help="Max concurrent API calls")
    parser.add_argument("--max-tokens", type=int, default=2048, help="Max tokens per response")
    parser.add_argument("--temperature", type=float, default=0.8, help="Sampling temperature")
    parser.add_argument("--prompt-file", default=None, help="File with one prompt per line (cycles if < num-samples)")
    parser.add_argument("--prompt", default=None, help="Single prompt to use for all samples")
    parser.add_argument("--max-retries", type=int, default=5, help="Max retries on rate-limit/server errors")
    # [EXTENDED by dsv4-pro] Added --temperature and --max-retries; KAT-Coder had only --model, --num-samples, --output, --concurrency, --max-tokens
    return parser.parse_args()


def load_prompts(args):
    if args.prompt:
        return [args.prompt] * args.num_samples

    if args.prompt_file:
        with open(args.prompt_file) as f:
            lines = [line.strip() for line in f if line.strip()]
        if not lines:
            raise SystemExit("Prompt file is empty")
        return [lines[i % len(lines)] for i in range(args.num_samples)]

    topics = [
        # [GENERATED by KAT-Coder, extended by dsv4-pro] First 10 from KAT-Coder, remaining 15 added by dsv4-pro
        "Explain quantum computing to a five-year-old.",
        "Write a haiku about recursion.",
        "Describe the color blue to someone blind since birth.",
        "Explain why the sky is blue using only analogies.",
        "Write a short story about a number that gained consciousness.",
        "Describe the taste of water to an alien.",
        "Explain blockchain to a medieval peasant.",
        "Write a recipe for patience.",
        "Describe silence in exactly ten words.",
        "Explain the concept of zero to an ancient philosopher.",
        "Write a Python function that implements binary search.",
        "Design a REST API for a task management app. Write the OpenAPI spec.",
        "Write a SQL query that finds duplicate records in a users table.",
        "Explain the difference between TCP and UDP using a restaurant analogy.",
        "Write a bash one-liner that finds the 10 largest files in a directory tree.",
        "Generate a JSON schema for a blog post object.",
        "Write pytest unit tests for a function that validates email addresses.",
        "Explain Docker to a developer who has never used containers.",
        "Write a regex that matches valid IPv4 addresses.",
        "Describe how a JWT token works step by step.",
        "Write a Makefile for a Python project with lint, test, and build targets.",
        "Explain how garbage collection works in Python.",
        "Write a systemd unit file for a Python web service.",
        "Document a git workflow for a team of 5 developers.",
        "Generate 10 creative coding challenge prompts for a junior developer interview.",
    ]
    return [topics[i % len(topics)] for i in range(args.num_samples)]


class SyntheticDataGenerator:
    def __init__(self, args):
        self.args = args
        self.api_key = os.environ.get("OPENROUTER_API_KEY")
        if not self.api_key:
            raise RuntimeError("OPENROUTER_API_KEY environment variable is not set")

        # [GENERATED by KAT-Coder] Core async client init and retry logic
        self.client = AsyncOpenAI(
            api_key=self.api_key,
            base_url="https://openrouter.ai/api/v1",
        )
        self.results: list[dict] = []
        self.failed: int = 0          # [ADDED by dsv4-pro]
        self.rate_limited: int = 0    # [ADDED by dsv4-pro]
        self.total_tokens: int = 0    # [ADDED by dsv4-pro]
        self._shutdown = False
        self._start_time: float = 0.0 # [ADDED by dsv4-pro]

    # [GENERATED by KAT-Coder] Exponential backoff retry with Retry-After header support
    async def _retry_request(self, **kwargs):
        max_retries = self.args.max_retries
        base_backoff = 2.0
        for attempt in range(max_retries + 1):
            try:
                response = await self.client.chat.completions.create(**kwargs)
                return response
            except Exception as e:
                status_code = getattr(getattr(e, "response", None), "status_code", None)

                if status_code == 429:
                    self.rate_limited += 1
                if status_code not in (429, 500, 502, 503, 504) or attempt == max_retries:
                    raise

                wait = base_backoff * (2 ** attempt)
                retry_after = getattr(getattr(e, "response", None), "headers", {}).get("Retry-After")
                if retry_after:
                    try:
                        wait = float(retry_after)
                    except (ValueError, TypeError):
                        pass
                tqdm.write(f"  Rate-limited (429), retrying in {wait:.1f}s (attempt {attempt + 1}/{max_retries})")
                await asyncio.sleep(wait)
        raise RuntimeError("Max retries exceeded")

    async def _generate_one(self, i: int, prompt: str, semaphore: asyncio.Semaphore):
        if self._shutdown:
            return None

        async with semaphore:
            try:
                response = await self._retry_request(
                    model=self.args.model,
                    messages=[{"role": "user", "content": prompt}],
                    max_tokens=self.args.max_tokens,
                    temperature=self.args.temperature,
                )
                content = response.choices[0].message.content or ""
                tokens = response.usage.total_tokens if response.usage else 0
                self.total_tokens += tokens  # [ADDED by dsv4-pro]

                return {
                    "id": str(uuid.uuid4()),
                    "model": self.args.model,
                    "prompt": prompt,
                    "response": content,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "tokens": tokens,
                }
            except Exception as e:
                self.failed += 1
                tqdm.write(f"  Sample {i} failed: {e}")
                return {
                    "id": str(uuid.uuid4()),
                    "model": self.args.model,
                    "prompt": prompt,
                    "response": None,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    "error": str(e),
                }

    async def run(self):
        prompts = load_prompts(self.args)
        semaphore = asyncio.Semaphore(self.args.concurrency)
        self._start_time = time.time()

        tqdm.write(f"Model: {self.args.model}")
        tqdm.write(f"Samples: {len(prompts)}, Concurrency: {self.args.concurrency}")
        tqdm.write(f"Output: {self.args.output}\n")

        pbar = tqdm(total=len(prompts), desc="Generating", unit="sample", smoothing=0.1)

        tasks = [self._generate_one(i, prompt, semaphore) for i, prompt in enumerate(prompts)]
        # [FIXED by dsv4-pro] KAT-Coder used asyncio.gather + manual Queue.put/Queue.get.
        # gather() waits for all tasks to finish, then the Queue drain loop runs.
        # On SIGINT/shutdown, in-flight tasks may complete but their results sit in
        # the Queue unread. asyncio.as_completed yields results as they finish,
        # ensuring no results are lost on early exit.
        for coro in asyncio.as_completed(tasks):
            if self._shutdown:
                break
            result = await coro
            if result is not None:
                self.results.append(result)
            pbar.update(1)

        pbar.close()

    def save(self):
        os.makedirs(os.path.dirname(self.args.output) or ".", exist_ok=True)  # [ADDED by dsv4-pro] prevent FileNotFoundError on nested paths
        with open(self.args.output, "w") as f:
            for record in self.results:
                f.write(json.dumps(record, ensure_ascii=False) + "\n")  # [ADDED by dsv4-pro] ensure_ascii=False for non-latin content
        tqdm.write(f"\nSaved {len(self.results)} records to {self.args.output}")

    def print_summary(self):
        elapsed = time.time() - self._start_time
        successful = [r for r in self.results if r.get("response") is not None]
        failed_records = [r for r in self.results if r.get("response") is None]

        # [ENHANCED by dsv4-pro] Added throughput, avg response length, rate-limited count
        print(f"\n{'=' * 60}")
        print(f"  Synthetic Data Generation Summary")
        print(f"{'=' * 60}")
        print(f"  Model:             {self.args.model}")
        print(f"  Total requested:   {self.args.num_samples}")
        print(f"  Successful:        {len(successful)}")
        print(f"  Failed:            {len(failed_records)}")
        print(f"  Rate-limited:      {self.rate_limited}")
        print(f"  Total tokens:      {self.total_tokens:,}")
        print(f"  Elapsed:           {elapsed:.1f}s")
        if successful:
            avg_len = sum(len(r.get("response", "")) for r in successful) / len(successful)
            print(f"  Avg response len:  {avg_len:.0f} chars")
            print(f"  Throughput:        {len(successful) / elapsed:.2f} samples/s")
        print(f"  Output:            {self.args.output}")
        print(f"{'=' * 60}\n")


async def main():
    args = parse_args()
    generator = SyntheticDataGenerator(args)

    # [FIXED by dsv4-pro] KAT-Coder wrote:
    #   signal.signal(signal.SIGINT, self._handle_signal)
    # This passes a bound method as the handler. When the signal fires, Python
    # calls it without the instance context, so `self._shutdown = True` inside
    # _handle_signal raises AttributeError. Fixed by using a closure +
    # loop.add_signal_handler (preferred on Unix) with signal.signal fallback.
    loop = asyncio.get_running_loop()
    shutdown_event = asyncio.Event()

    def _on_signal():
        generator._shutdown = True
        shutdown_event.set()
        tqdm.write("\nReceived interrupt, finishing in-flight requests...")

    for sig in (signal.SIGINT, signal.SIGTERM):
        try:
            loop.add_signal_handler(sig, _on_signal)
        except NotImplementedError:
            signal.signal(sig, lambda *_: _on_signal())

    # [FIXED by dsv4-pro] KAT-Coder called generator.run() without try/finally,
    # so on unhandled exceptions the save+summary would be skipped.
    try:
        await generator.run()
    finally:
        generator.save()
        generator.print_summary()


if __name__ == "__main__":
    asyncio.run(main())
